import { Download, FileText, FileJson } from 'lucide-react'
import type { AnalysisResults, AnalysisSummary } from '../App'

interface ExportReportProps {
  results: AnalysisResults | null
  summary: AnalysisSummary | null
}

export default function ExportReport({ results, summary }: ExportReportProps) {
  const exportAsMarkdown = () => {
    if (!results || !summary) return

    const markdown = generateMarkdownReport(results, summary)
    downloadFile(markdown, 'design-qa-report.md', 'text/markdown')
  }

  const exportAsJSON = () => {
    if (!results || !summary) return

    const json = JSON.stringify({ results, summary, timestamp: new Date().toISOString() }, null, 2)
    downloadFile(json, 'design-qa-report.json', 'application/json')
  }

  const exportWCAGReport = () => {
    if (!results || !summary) return

    const wcagReport = generateWCAGReport(results, summary)
    downloadFile(wcagReport, 'wcag-compliance-report.md', 'text/markdown')
  }

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const generateMarkdownReport = (results: AnalysisResults, summary: AnalysisSummary): string => {
    const date = new Date().toLocaleDateString()
    
    let md = `# DesignQA Report\n\n`
    md += `**Generated:** ${date}\n\n`
    md += `---\n\n`
    
    md += `## Summary\n\n`
    md += `- **Layers Analyzed:** ${summary.total}\n`
    md += `- **Issues Found:** ${summary.issues}\n`
    md += `- **Critical Issues:** ${summary.critical}\n`
    md += `- **Quality Score:** ${Math.max(0, Math.round(100 - (summary.issues / summary.total) * 10))}%\n\n`
    
    md += `---\n\n`
    
    // Accessibility Issues
    if (results.accessibility.length > 0) {
      md += `## 🔴 Accessibility Issues (${results.accessibility.length})\n\n`
      results.accessibility.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n`
        md += `- **Auto-fixable:** ${issue.autoFixable ? 'Yes' : 'No'}\n`
        if (issue.details) {
          md += `- **Details:**\n`
          Object.entries(issue.details).forEach(([key, value]) => {
            md += `  - ${key}: ${value}\n`
          })
        }
        md += `\n`
      })
    }
    
    // Structure Issues
    if (results.structure.length > 0) {
      md += `## 🔵 Structure Issues (${results.structure.length})\n\n`
      results.structure.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n\n`
      })
    }
    
    // Typography Issues
    if (results.typography.length > 0) {
      md += `## 🟡 Typography Issues (${results.typography.length})\n\n`
      results.typography.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n\n`
      })
    }
    
    // Layout Issues
    if (results.layout.length > 0) {
      md += `## 🟣 Layout Issues (${results.layout.length})\n\n`
      results.layout.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n\n`
      })
    }
    
    // Components Issues
    if (results.components.length > 0) {
      md += `## 🟢 Component Issues (${results.components.length})\n\n`
      results.components.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n\n`
      })
    }
    
    // Prototypes Issues
    if (results.prototypes && results.prototypes.length > 0) {
      md += `## 🔗 Prototype Issues (${results.prototypes.length})\n\n`
      results.prototypes.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.message}\n\n`
        md += `- **Layer:** \`${issue.nodeName}\`\n`
        md += `- **Severity:** ${issue.severity}\n\n`
      })
    }
    
    md += `---\n\n`
    md += `*Generated by DesignQA - AI-Powered Design Auditor*\n`
    
    return md
  }

  const generateWCAGReport = (results: AnalysisResults, summary: AnalysisSummary): string => {
    const date = new Date().toLocaleDateString()
    
    let md = `# WCAG Compliance Report\n\n`
    md += `**Generated:** ${date}\n\n`
    md += `---\n\n`
    
    const a11yIssues = results.accessibility
    const criticalCount = a11yIssues.filter(i => i.severity === 'critical').length
    const warningCount = a11yIssues.filter(i => i.severity === 'warning').length
    
    md += `## Compliance Status\n\n`
    
    if (criticalCount === 0) {
      md += `✅ **WCAG AA Compliant** (No critical issues)\n\n`
    } else {
      md += `❌ **Not WCAG Compliant** (${criticalCount} critical issues)\n\n`
    }
    
    md += `### Issue Breakdown\n\n`
    md += `- 🔴 Critical: ${criticalCount}\n`
    md += `- 🟡 Warnings: ${warningCount}\n`
    md += `- ℹ️ Info: ${a11yIssues.length - criticalCount - warningCount}\n\n`
    
    md += `---\n\n`
    
    // Contrast Issues
    const contrastIssues = a11yIssues.filter(i => i.type === 'contrast')
    if (contrastIssues.length > 0) {
      md += `## Contrast Issues (WCAG 1.4.3)\n\n`
      contrastIssues.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.nodeName}\n\n`
        md += `**Issue:** ${issue.message}\n\n`
        if (issue.details) {
          md += `- Contrast Ratio: ${issue.details.contrast}:1\n`
          md += `- Required: ${issue.details.required}:1\n`
          md += `- Text Color: ${issue.details.textColor}\n`
          md += `- Background: ${issue.details.bgColor}\n`
          md += `- WCAG Level: ${issue.details.wcagLevel}\n\n`
        }
      })
    }
    
    // Touch Target Issues
    const touchIssues = a11yIssues.filter(i => i.type === 'touch-target')
    if (touchIssues.length > 0) {
      md += `## Touch Target Issues (WCAG 2.5.5)\n\n`
      touchIssues.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.nodeName}\n\n`
        md += `**Issue:** ${issue.message}\n\n`
        if (issue.details) {
          md += `- Current Size: ${issue.details.width}x${issue.details.height}px\n`
          md += `- Required: ${issue.details.required}x${issue.details.required}px\n\n`
        }
      })
    }
    
    // Readability Issues
    const readabilityIssues = a11yIssues.filter(i => i.type === 'readability')
    if (readabilityIssues.length > 0) {
      md += `## Readability Issues\n\n`
      readabilityIssues.forEach((issue, i) => {
        md += `### ${i + 1}. ${issue.nodeName}\n\n`
        md += `**Issue:** ${issue.message}\n\n`
      })
    }
    
    md += `---\n\n`
    md += `## Recommendations\n\n`
    
    if (criticalCount > 0) {
      md += `### Critical Actions Required\n\n`
      md += `1. Address all contrast ratio issues to meet WCAG AA standards (4.5:1 for normal text, 3:1 for large text)\n`
      md += `2. Ensure all interactive elements meet minimum touch target size of 48x48px\n`
      md += `3. Review and fix readability issues for better user experience\n\n`
    }
    
    md += `### Best Practices\n\n`
    md += `- Test with screen readers and keyboard navigation\n`
    md += `- Verify color contrast in different lighting conditions\n`
    md += `- Ensure sufficient spacing between interactive elements\n`
    md += `- Use semantic naming for better accessibility\n\n`
    
    md += `---\n\n`
    md += `*Generated by DesignQA - AI-Powered Design Auditor*\n`
    
    return md
  }

  if (!results || !summary) {
    return (
      <div className="text-center py-12">
        <FileText size={48} className="mx-auto mb-4 text-figma-text-secondary" />
        <h3 className="text-lg font-medium mb-2">No Data to Export</h3>
        <p className="text-sm text-figma-text-secondary">
          Run an analysis first to generate reports
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="bg-figma-bg-hover rounded-lg p-4">
        <h3 className="font-medium mb-2">Export Report</h3>
        <p className="text-xs text-figma-text-secondary">
          Export your design analysis in various formats for documentation and sharing with your team.
        </p>
      </div>

      {/* Export Options */}
      <div className="space-y-3">
        {/* Markdown Report */}
        <button
          onClick={exportAsMarkdown}
          className="w-full bg-figma-bg-hover hover:bg-figma-border p-4 rounded-lg text-left transition-colors group"
        >
          <div className="flex items-start gap-3">
            <div className="p-2 bg-blue-500/20 rounded-lg group-hover:bg-blue-500/30 transition-colors">
              <FileText size={20} className="text-blue-400" />
            </div>
            <div className="flex-1">
              <h4 className="text-sm font-medium mb-1">Markdown Report</h4>
              <p className="text-xs text-figma-text-secondary">
                Complete analysis report in Markdown format. Perfect for README files and documentation.
              </p>
              <div className="flex items-center gap-2 mt-2">
                <Download size={14} className="text-figma-primary" />
                <span className="text-xs text-figma-primary">design-qa-report.md</span>
              </div>
            </div>
          </div>
        </button>

        {/* JSON Report */}
        <button
          onClick={exportAsJSON}
          className="w-full bg-figma-bg-hover hover:bg-figma-border p-4 rounded-lg text-left transition-colors group"
        >
          <div className="flex items-start gap-3">
            <div className="p-2 bg-purple-500/20 rounded-lg group-hover:bg-purple-500/30 transition-colors">
              <FileJson size={20} className="text-purple-400" />
            </div>
            <div className="flex-1">
              <h4 className="text-sm font-medium mb-1">JSON Data</h4>
              <p className="text-xs text-figma-text-secondary">
                Raw analysis data in JSON format. Ideal for integration with other tools and CI/CD pipelines.
              </p>
              <div className="flex items-center gap-2 mt-2">
                <Download size={14} className="text-figma-primary" />
                <span className="text-xs text-figma-primary">design-qa-report.json</span>
              </div>
            </div>
          </div>
        </button>

        {/* WCAG Report */}
        <button
          onClick={exportWCAGReport}
          className="w-full bg-figma-bg-hover hover:bg-figma-border p-4 rounded-lg text-left transition-colors group"
        >
          <div className="flex items-start gap-3">
            <div className="p-2 bg-green-500/20 rounded-lg group-hover:bg-green-500/30 transition-colors">
              <FileText size={20} className="text-green-400" />
            </div>
            <div className="flex-1">
              <h4 className="text-sm font-medium mb-1">WCAG Compliance Report</h4>
              <p className="text-xs text-figma-text-secondary">
                Focused accessibility report with WCAG guidelines. Essential for compliance documentation.
              </p>
              <div className="flex items-center gap-2 mt-2">
                <Download size={14} className="text-figma-primary" />
                <span className="text-xs text-figma-primary">wcag-compliance-report.md</span>
              </div>
            </div>
          </div>
        </button>
      </div>

      {/* Summary */}
      <div className="bg-figma-bg-hover rounded-lg p-4">
        <h4 className="text-sm font-medium mb-3">Report Summary</h4>
        <div className="grid grid-cols-2 gap-3 text-xs">
          <div>
            <div className="text-figma-text-secondary mb-1">Total Issues</div>
            <div className="text-lg font-semibold">{summary.issues}</div>
          </div>
          <div>
            <div className="text-figma-text-secondary mb-1">Critical</div>
            <div className="text-lg font-semibold text-red-400">{summary.critical}</div>
          </div>
          <div>
            <div className="text-figma-text-secondary mb-1">Layers</div>
            <div className="text-lg font-semibold">{summary.total}</div>
          </div>
          <div>
            <div className="text-figma-text-secondary mb-1">Score</div>
            <div className="text-lg font-semibold text-figma-primary">
              {Math.max(0, Math.round(100 - (summary.issues / summary.total) * 10))}%
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
